"""
Package landmapyr.

Functions:
    cached.cached(func_key, override)
    cdcplaces.download_census_tract(tract_path, placename)
    cdcplaces.download_cdc_disease(data_dir)
    cdcplaces.join_tract_cdc(place_tract_gdf, cdc_df)
    cdcplaces.shp_tract_path(data_dir, place)
    check.check_element_in_csv(filename, column_name, target_value)
    check.check_naip_tracts(naip_index_path, naip_scenes_df)
    check.get_last_row_csv(file_path)
    check.header_csv(file_path)
    explore.index_tree(redlining_index_gdf)
    explore.ramp_logic(data, up, down)
    explore.train_test(model_df)
    explore.var_trans(ndvi_cdc_gdf)
    gbif.count_monthly_ecoregions(gbif_ecoregions_gdf, region_type, occurrence_name)
    gbif.count_yearly_ecoregions(gbif_ecoregions_gdf, region_type, occurrence_name)
    gbif.download_gbif(gbif_dir, species_key, year, unzip, reset)
    gbif.ecoregions(data_dir)
    gbif.gbif_credentials(reset)
    gbif.gbif_monthly(gbif_df)
    gbif.gbif_species_key(species_name)
    gbif.join_ecoregions_monthly(ecoregions_gdf, monthly_gdf)
    gbif.join_occurrence(ecoregions_gdf, occurrence_gdf)
    gbif.load_gbif(gbif_path)
    gbif.simplify_ecoregions_gdf(ecoregions_gdf)
    gvplot.gvplot_chloropleth(gdf)
    gvplot.gvplot_gdf_esri(place_gdf)
    gvplot.gvplot_ndvi_index(place_gdf)
    gvplot.gvplot_resid(model_df, reg)
    hvplot.hvplot_index_grade(redlining_index_gdf, place)
    hvplot.hvplot_index_pred(redlining_index_gdf, tree_classifier, place)
    hvplot.hvplot_occurrence(occurrence_gdf, unit)
    hvplot.hvplot_matrix(model_df)
    hvplot.hvplot_tract_gdf(place_tract_gdf)
    hvplot.hvplot_train_test(y_test)
    initial.create_data_dir(new_dir)
    initial.robust_code()
    naip.check_element_in_csv(filename, column_name, target_value)
    naip.download_naip_scenes(naip_index_path, tract_cdc_gdf)
    naip.merge_ndvi_cdc(tract_cdc_gdf, ndvi_index_df)
    naip.naip_path(data_dir, place):
    naip.ndvi_naip_one(tract_cdc_gdf, tract, tract_date_gdf)
    naip.ndvi_naip_df(naip_index_path, tract_cdc_gdf, naip_scenes_df)
    plot.plot_cluster(rgb_sat, model_df)
    plot.plot_das(das)
    plot.plot_index(index_da, place)
    plot.plot_gdf_da(place_gdf, index_da)
    plot.plot_gdf_state(place_gdf)
    plot.plot_gdfs_map(place_gdf)
    plot.plot_matrix(model_df)
    plot.plot_train_test(y_test)
    polaris.merge_soil(place_gdf, soil_var, soil_sum=, soil_depth, buffer)
    polaris.soil_url_dict(place_gdf, soil_var, soil_sum, soil_depth)
    process.clip_gdf_da_bounds(place_gdf, da, buffer)
    process.da2gdf(data_array)
    process.process_bands(city_gdf, raster_df)
    process.process_cloud_mask(cloud_uri, bounds_gdf, bits_to_mask)
    process.process_image(uri, bounds_gdf)
    process.process_metadata(city_files)
    redline.redline_gdf(data_dir)
    redline.redline_index_gdf(redlining_gdf, index_stats)
    redline.redline_mask(place_gdf, index_da)
    reflect.compute_reflectance_da(search_results, boundary_gdf)
    reflect.merge_and_composite_arrays(granule_da_df)
    reflect.read_delta_gdf(huc_level, watershed)
    reflect.read_wbd_file(wbd_filename, huc_level, cache_key)
    reflect.reflectance_kmeans(reflectance_da)
    reflect.reflectance_range(model_df)
    reflect.reflectance_rgb(reflectance_da)
    srtm.srtm_download(place_gdf, elevation_dir, buffer)
    srtm.srtm_slope(srtm_da)
    thredds.maca_year(maca_df, row, year)
    thredds.process_maca(sites, scenarios, climates, years, buffer)
"""