"""
Post-render script to move images generated by Quarto (using Jupyter).

When rendering Quarto .qmd documents that use the Python (Jupyter) engine, 
Pandoc extracts embedded Jupyter media into a relative directory structured 
as `[filename]_files/figure-[format]/` during the rendering process.

This script acts as a Quarto post-render hook to automatically move those 
images to a cleaner `images/[filename]` directory and update the markdown 
links in the generated .md file.

Usage in Quarto YAML header:
---
title: "Document Title"
jupyter: python3
post-render:
  - python move_images.py [filename]
---
"""
import os
import sys
import shutil
import re

def move_images(filename: str):
    """
    Move images from the default Quarto Jupyter output directory to a custom
    directory, and update the markdown links to point to the new location.

    Args:
        filename (str): The basename of the rendered Quarto document (without extension).
    """
    source_dir = f"{filename}_files/figure-markdown"
    target_dir = f"images/{filename}"
    md_file = f"{filename}.md"

    if os.path.exists(source_dir):
        os.makedirs(target_dir, exist_ok=True)
        
        # 1. Move the image files
        for img in os.listdir(source_dir):
            shutil.move(os.path.join(source_dir, img), os.path.join(target_dir, img))
            
        # 2. Clean up the old empty directory
        shutil.rmtree(f"{filename}_files")
        
        # 3. Update the markdown links in the .md file
        if os.path.exists(md_file):
            with open(md_file, "r") as f:
                content = f.read()
                
            content = re.sub(rf"{filename}_files/figure-markdown/", f"{target_dir}/", content)
            
            with open(md_file, "w") as f:
                f.write(content)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Please provide the document basename.")
        sys.exit(1)

    filename_arg = sys.argv[1] # e.g., 'madison'
    move_images(filename_arg)